import unittest

from reasoning.rejection_forward_test import RejectionForwardTest
from reasoning.rejection_backward_test import RejectionBackwardTest

from representation.formula_qubit_preparation import PreparationTest

unittest.main()